## `lab09`—Debugging

![](./img/lab10-header-bkgd.png)

Objectives

-   Learn how to debug code using a standard process of investigation.
-   Assess peer code to identify strengths and weaknesses.

This activity-based lab will challenge you to apply a flowchart process to debug codes so that they perform as intended.  The lab is divided into two segments:  Debugging and Peer Assessment.

Because portions of this lab are individual, you should record your work and submit your own notebook for the lab grade.

### Debugging Activity (25 minutes)

The first part of the lab, Debugging, will ask you to examine a code with a stated objective.  Unfortunately, this code was sloppily written and several bugs were introduced during its composition.  Your goal is to identify and correct all of those bugs.  You will have 15 minutes (timed) to work on identifying and fixing bugs alone, and then 5 minutes with a team of three students to finish it up.  The TA then has 5 minutes to clear up any questions that arose.

---

Wait for your TA to tell you to start and then work on debugging the following code.

In [24]:
# This code should accept a positive nonzero integer from the user.
# It should then calculate all integral factors of that number.

# The following code contains NOT LESS THAN FIVE bugs.
# It should pass the following test cases:
#   100 -> 100, 50, 25, 20, 10, 5, 4, 2, 1
#   69 -> 69, 23, 3, 1
#   14.5 -> should be rejected (not raise exception)
#   a -> should be rejected (not raise exception)
#   0 -> should be rejected (not raise exception)

#########################################################
def is_divisible( a, b ):
    """
    Determine if integer a is divisible by integer b.
    """

    remainder = a % b

    # if remainder is zero, then a is divisible by b
    if remainder == 0:
        return "true"


#########################################################
def find_divisors( integer ):
    """
    Find all divisors of an integer and return them as a list.
    """

    divisors = []
    # we know that an integer divides itself
    divisors.append(integer)

    # we also know that the biggest divisor other than the integer
    # itself must be at most half the value of the integer
    divisor = int(integer / 2)

    while divisor > 0:
        if is_divisible(integer, divisor)== 'true':
            divisors.append(divisor)
        divisor -= 1

    return divisors


#########################################################
def main():
    input_a = input('a=')

    # do some checking of the user's input
    # is it a number?
    if input_a.isdigit():
        a = int(input_a)
    else:
        print( 'Please enter an integer.' )
        return
        

    # is it nonnegative?
    if a <= 0:
        print( 'The number should be nonnegative.' )
        return

    divisors = find_divisors( a )

    # print the results
    print( "The divisors of %d are:" % a )
    for divisor in divisors:
        print ( divisor )

    

#########################################################
# This is the main entry point of the program.
if __name__ == '__main__':
    main()

a=0
The number should be nonnegative.


In [ ]:
# test the code here if necessary


# It should pass the following test cases:
#   100 -> 100, 50, 25, 20, 10, 5, 4, 2, 1
#   69 -> 69, 23, 3, 1
#   14.5 -> should be rejected (not raise exception)
#   a -> should be rejected (not raise exception)
#   0 -> should be rejected (not raise exception)


In [ ]:
# test the code here if necessary

---

### Peer Assessment Activity (60 minutes)

In order to carry out the peer assessment portion of this lab, you are going to examine submissions which other students made for `exam3`.  These are anonymized by random numbers, and each team will receive a different set of submissions to assess.

Enter the four numbers given you by your TA here: 

In [25]:
import numpy as np
test_cases = []
test_cases.append( np.random.choice( range( 5050,5710 ) ) )
test_cases.append( np.random.choice( range( 5050,5710 ) ) )
test_cases.append( np.random.choice( range( 7575,8163 ) ) )
test_cases.append( np.random.choice( range( 7575,8163 ) ) )
print( test_cases )

[5430, 5258, 7771, 7849]


The next cell will fetch your peer grading examples.  (Please take note of the `try`/`except` blocks.)

In [26]:
# retrieve peer submissions via randomized code
import os, shutil
for test_case in test_cases:
    try:
        filepath = os.path.join( '/class/cs101/data/hashes','%i.py'%test_case )
        shutil.copy2( filepath, '.' )
    except FileNotFoundError:
        print( 'Please try again.  I was unable to locate %s.py; do you have the correct number?'%test_case )
        break

You have now received four peer submissions in your `lab09` directory.  Your task is to assess these codes, critique them for correctness and style, and record that critique below.

Examine the file in another window (either on the command line or in a text editor).  You can also run the codes on the command line using `python XXX.py`, where `XXX` is the number.

Double-click a cell below to edit it.  In each cell, enter the number of the code you are assessing.  Then answer the questions as thoroughly as you can.  You have ten minutes available to assess each code---get as much done as you can in that time.  Then you can work in your groups (or discuss, as your TA decides) for five minutes.

### `exam3_linspace`

We wish to generate $n$ equally-spaced $x$ coordinates in $[a,b]$.  In this figure, these correspond to the vertical dividing lines between segments.

![](repo:img/exam3-linspace.png)

**Compose a function `linspace( a,b,n )` which accepts a left-hand bound `a`, a right-hand bound `b` (both `float`s), and a number of intervals `n` (an `int`), and returns a `list` containing the coordinates dividing the space equally.**  `n` should be optional with a default value of `11`.  You may assume that $b > a$.

For instance, `linspace( 0,1 )` should return the list:

    [ 0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0 ]

while `linspace( 0,10,n=10 )` should return the list:

    [ 0.0,1.11111111,2.22222222,3.33333333,4.44444444,5.55555556,6.66666667,7.77777778,8.88888889,10.0 ]

Note that both the left- and right-hand bounds are *included*.  You may use a `for` loop or a `while` loop to implement the solution to this question.  You may also assume that $a<b$, so don't worry about testing or swapping those values.  Finally, please note that small numerical errors are permissible, _e.g._, `1.00000004` or similar.

A formula for the $i$th element is

$$
x_{i}
=
a + i \frac{(b-a)}{n-1}
\text{.}
$$

<div class="alert alert-danger">
Importing <code>linspace</code> from a library will not work.  Work with lists here, not NumPy arrays.
</div>

### Peer Code Assessment #1:  `exam3_linspace`

(Double-click on the text to edit it.)

- Which code number are you assessing?  7771

#### Correctness

- Does this code define a function `linspace`? Yes

- Does the function `linspace` return the proper type? Linspace correclty returns a list. 

- Is the approach generally valid? Yes, the general approach is valid. The for loop is implemented and the function returns proper values. (I.e., if one or two things were adjusted, would the code work properly?)

- What needs to be corrected?  (You can write code or explanations here.)



#### Style

- Is the code well-documented? it's well-documented 

- Are the variable names descriptive? The variables names are straighforward 

- Are line breaks and formatting conducive to reading and understanding the code? The coad is easy to understand. 

- Do all parts of the code play a rôle or are some of them unnecessary? all parts of the code play a role

### Peer Code Assessment #2:  `exam3_linspace`

- Which code number are you assessing?  7849

#### Correctness

- Does this code define a function `linspace`? Yes, it does

- Does the function `linspace` return the proper type? Yes, it returns a list

- Is the approach generally valid?  The general approach is valid with the for loop implemented. But more than few things have to be chanegd for the code to work. 

- What needs to be corrected?  (You can write code or explanations here.)

def linspace(a , b , n=11):
    list = []
    for i in range(n):
        x = ((b-a)/ (n-1) * i + a)
        list.append(x)
    return list
    
#### Style

- Is the code well-documented? No, there are many unncessary lines. 

- Are the variable names descriptive? Yes, variable names are descriptive

- Are line breaks and formatting conducive to reading and understanding the code? Yes

- Do all parts of the code play a rôle or are some of them unnecessary? Many of the lines were unncessary: everything before the fore loop except lost ] [] was unncesseary. Defining x was unnecessary too.

###   `exam3_dict_str_parse`

Given a string, we wish to count the frequency of each letter in it using a dictionary.

**Compose a function `lettercount( text )` which accepts a `str` named `text` of a sample text and returns a `dict` with keys `'A'`, `'B'`, ..., `'Z'` which correspond to values indicating the number of times each letter occurs in `text`.**

For instance, given the string:

    text0 = "As kingfishers catch fire, dragonflies draw flame"

`lettercount( text0 )` should return the dictionary

    { 'A': 5, 'B': 0, 'C': 2, 'D': 2, 'E': 4,
      'F': 4, 'G': 2, 'H': 2, 'I': 4, 'J': 0,
      'K': 1, 'L': 2, 'M': 1, 'N': 2, 'O': 1,
      'P': 0, 'Q': 0, 'R': 4, 'S': 4, 'T': 1,
      'U': 0, 'V': 0, 'W': 1, 'X': 0, 'Y': 0,
      'Z': 0 }


### Peer Code Assessment #3:  `exam3_dict_str_parse`

- Which code number are you assessing?  5430

#### Correctness

Write a program which implements a loop evolving pentadecathlon for thirty time steps. You should implement a list of ndarrays named pd_list, each containing a single generation of pentadecathlon's evolution.


- Does this code implement a function `lettercount` correctly? No, they did not. The code does not work. 

- Is the approach generally valid?  (I.e., if one or two things were adjusted, would the code work properly?) No. the code is not even finished. 

- What needs to be corrected?  (You can write code or explanations here.)
The for loop has to be implemented. There needs to be return statement at the end. 



#### Style

- Is the code well-documented? No. 

- Are the variable names descriptive? No

- Are line breaks and formatting conducive to reading and understanding the code? Yes

- Do all parts of the code play a rôle or are some of them unnecessary? The last line is incomplete because there is no return statement. 

### Peer Code Assessment #4:  `exam3_dict_str_parse`

- Which code number are you assessing?  5258

#### Correctness

Write a program which implements a loop evolving pentadecathlon for thirty time steps. You should implement a list of ndarrays named pd_list, each containing a single generation of pentadecathlon's evolution.


- Does this code implement a function `lettercount` correctly? No, the function does nto work. 

- Is the approach generally valid?  The general approach is valid. (I.e., if one or two things were adjusted, would the code work properly?)

- What needs to be corrected?  (You can write code or explanations here.)
He/she needs to append a new letter and count to the dictionary instead of returning the empty dictionary.  


#### Style

- Is the code well-documented? yes. 

- Are the variable names descriptive? yes

- Are line breaks and formatting conducive to reading and understanding the code? yes

- Do all parts of the code play a rôle or are some of them unnecessary? no some lines such as key=letter are unncessary 